#!/usr/bin/python

import matplotlib.pyplot as plt
import numpy as np
import sys
import math

x = [ ]
y = [ ]
k = 0
i = float(-2)
tmp = float(0)

if (len(sys.argv) != 3):
    sys.exit("Nombre d'arguments invalides.")
a = sys.argv[1]
if (a < 2):
    sys.exit("Le premier argument (a) doit etre superieur a 2.")

try:
    a = float(a)
except:
    print ("Le premier argument (a) doit etre un nombre.")

try:
    nmax = float(sys.argv[2])
except:
    print ("Le deuxieme argument (nmax) doit etre un nombre.")

try:
    while (i <= 2) :
        while (k <= nmax) :
            tmp = (tmp + ((math.cos(((a ** k)) * (math.pi) * i)) / (2 ** k)))
            k = k + 1
        x.append(i)
        y.append(tmp)
        tmp = float(0)
        k = float(0)
        i = i + 0.001
except:
    sys.exit("Nombre(s) trop grand(s).")

try:
    plt.plot(x,y, 'g-')
    plt.title("108Monstre", fontsize = 20)
    plt.xlabel("x", fontsize = 16, color = 'red')
    plt.ylabel("y", fontsize = 16, color = 'red')
    plt.show()
except:
    print ("Can not display.")
